### ISSUE TITLE
How do one define the recieving subject of a credential?

### ISSUE THREAD

**Issue by vongohren** [w3c-ccg/vc-api-test-suite-implementations#15]
I see that one defines issuer in the implementation, and id seems to be the issuer ID? And authenticated towards allowing to issue on behalf of that ID.

But where do one define the subject of a credential or what is the output?

**Comment by aljones15** [comment]
The tests themselves define the subject of a credential. So far the `credentialSubject`s are pretty simple:

https://github.com/w3c-ccg/vc-api-issuer-test-suite/blob/main/tests/validVc.json

We're hoping to use more complex `credentialSubject`s in the future, but right now as simple as possible is what we use. The output from the issuer should match the VC-API which means the body should be the issued credential.

**Comment by vongohren** [comment]
@aljones15 perfect, thanks for the info. But we define the issuer did right when building a test case? And that means the endpoint should be able to deliver a signed VC from a request of the test right?

**Comment by aljones15** [comment]
> @aljones15 perfect, thanks for the info. But we define the issuer did right when building a test case? And that means the endpoint should be able to deliver a signed VC from a request of the test right?

I'm not 100% sure on exactly what you mean here, but if you want to include an `issuer` property when adding your issuer to the `issuers` array, we can use that issuer in the test data. I know the VC HTTP API tests used to do that, but the `issuer` property was dropped at some point.

**Comment by vongohren** [comment]
Thanks for information, it seems I understand more now of the workings of the test suite :)
It does seem logical. I would expect the caller, the test, to identify itself to who they are issuing as.

**Comment by aljones15** [comment]
> 

the issuer might not be set right in the test suite, so you might have a point.
feel free to add an issuer if you want to.
