### ISSUE TITLE
Adding support for mavennet on test suites

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/vc-api-test-suite-implementations#7]
Hi Friends,

I do not currently have access to the secrets section of this repo ( or any of the other test suites), so I'm unable to update the relevant OAuth secrets.

is this the right repo to update the secrets and what is the format of said secrets?

**Comment by aljones15** [comment]
You will need to add it as an organization secret for w3c-ccg in general. Also, our oauth2 code is untested. If you could provide a client secret to us via email we could test locally and ensure everything is working.

**Comment by aljones15** [comment]
closing as oauth2 support has been implemented.
