### ISSUE TITLE
Update readme to point to all other test suite repos

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/vc-api-test-suite-implementations#9]
I'm assuming this is the "master" test suite repo, if so we should update readme with links to the various VC-API test suite repositories so we can have a centralized place for it.

**Comment by aljones15** [comment]
This is a good idea. We should probably add a note in the various test suites that use this package with something like: "If you want this test suite to run on your implementation then please add the tag `foo` to your issuer and verifier in implementations.". The wording of that needs to change.

**Comment by msporny** [comment]
> I'm assuming this is the "master" test suite repo, if so we should update readme with links to the various VC-API test suite repositories so we can have a centralized place for it.

I'm wondering if there is a way to auto-generate the list of packages that use this package via github reverse dependencies (or some other magic)?

**Comment by aljones15** [comment]
> > I'm assuming this is the "master" test suite repo, if so we should update readme with links to the various VC-API test suite repositories so we can have a centralized place for it.
> 
> I'm wondering if there is a way to auto-generate the list of packages that use this package via github reverse dependencies (or some other magic)?

You can search all of github and look in the code tab: https://github.com/search?q=vc-api-test-suite-implementations&type=code

There might be a more efficient way of doing it. Looks like only 3 test suites use it so far.

**Comment by aljones15** [comment]
test suites now link back to this repo:

https://github.com/w3c-ccg/vc-api-verifier-test-suite#implementation

https://github.com/w3c-ccg/vc-api-issuer-test-suite#implementation

https://github.com/w3c-ccg/di-ed25519-test-suite#implementation

**Comment by aljones15** [comment]
Closing as this seems to have been addressed.
